import type { Metadata } from "next";
import "./globals.css";

import { Noto_Serif_SC } from "next/font/google";

const notoSerifSC = Noto_Serif_SC({
  weight: ["200", "300", "400", "500", "600", "700", "900"],
  variable: "--font-noto-serif-sc",
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={notoSerifSC.className}>
      <body>{children}</body>
    </html>
  );
}
